pipeline{
    agent{
        docker {
            image 'maven:latest'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
        }
    }
    stages{
        stage("Checkout"){
            steps{
                sh 'echo passeed'
                //git branch: 'main', url: 'https://github.com/devopsjourney23/e2e-cicd-demo.git'
            }
        }
        stage('Build and Test'){
            steps {
                sh 'ls -ltr'
                // build the project and create a JAR file
                sh 'cd cicd-pipeline-01/spring-boot-app && mvn clean package'
            }
        }
    }
}